travis:
  secure:
    BINSTAR_TOKEN: KZKRvDHi690OT0FR0q6HSlY081QJOQDeCl3u5oFhsiK12JFLbvMs0Zni4eBvHGC4/Tc6O4zJ73/mB/4duE4NSGQI/iZkBY0U7LFW7awtFhnKJSjECoMkRxY53Krv1Sy0lZgfhphkiyndsnPLUZtrW55GE0cyJXttSyNrY+ILJH/rNBP2B/NDYuzS7KCkfkMfyQKKUg1ghMaHdWiyDqr4Vjot/BzwfIJVIK1LQU5JuVk7VWA64OC3InY8ZIMK2xz59Mu46z88oMSa6DzLDBFJR4wBOU3gHg79u5pWCpe74wIGhmptqKX4c7ecsoCPAJ3tk4JoOVVowo7kEtAUPSI4nsdcP/+EStZg1xL/MNBU0ySong21JSGIjbQ8cbX3oMDZcIFt8xD+ezA++MSqoG0PSu6soBHHAPL2/lt4scXZtd7iFyyJ6M0saWDgX2FNjM+gHimVVcsckp3oLYztyZF6H+Yi3ExF+cd5xP1qdgRNl+X6B6ouONnMi8izHUCXdSe8VpZDrGf6+PKgCAHoF9QxKm89apQRjMs7jyaf3a0FQ7nQsZs7F4fFipI2erFr1xmKu8DQ2OcphV4QpITpJkV9AuX93rVvNx720c1AsWy63rDNgkRrFaVlCYL7KxeiXQgV/nLCQmBBvttOEtD9rUk1HBqJ/4IWFyBq4i5rXYQYwCg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
